In [2]:
import numpy as np
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [5]:
a.ndim #number of dimensions (axes) of the array

1

In [7]:
a.shape #dimensions of the array

(3,)

In [10]:
a.size #equal to the product of elements of shape
len(a)
a.dtype #datatype of the elements in the array

dtype('int64')

In [13]:
b = np.array([[1.1,2.0,3.14],[4.22,5.54,6.3]])
b.shape

(2, 3)

In [15]:
b.ndim

2

In [17]:
b.shape

(2, 3)

In [19]:
b.size

6

In [21]:
b.dtype

dtype('float64')

In [23]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [25]:
b = np.array([[2,3],[4,5]])
b

array([[2, 3],
       [4, 5]])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.zeros((3,4,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [35]:
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [43]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [47]:
x = np.array([10,100,1000])
x

array([  10,  100, 1000])

In [49]:
y = np.arange(3)
y

array([0, 1, 2])

In [51]:
x + y

array([  10,  101, 1002])

In [53]:
x - y

array([ 10,  99, 998])

In [55]:
x * y

array([   0,  100, 2000])

In [59]:
y / x

array([0.   , 0.01 , 0.002])

In [61]:
x / 2

array([  5.,  50., 500.])

In [63]:
X = np.array([[1,2],[3,4]])
X

array([[1, 2],
       [3, 4]])

In [64]:
Y = np.array([[2,0],[3,4]])
Y

array([[2, 0],
       [3, 4]])

In [74]:
X + Y
X - Y
X * Y
X @ Y
X.dot(Y) #matrix multiplication
a = np.ones((2,3))
a += 9
a

array([[10., 10., 10.],
       [10., 10., 10.]])

In [77]:
a *= 2
a

array([[80., 80., 80.],
       [80., 80., 80.]])

In [80]:
y = np.arange(15)
y = np.arange(15).reshape(3,5) #transforming a 1d array into a 2d array
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
y = np.arange(15).reshape(4,4)

ValueError: cannot reshape array of size 15 into shape (4,4)

In [84]:
y.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
y.T #transpose

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [88]:
a = np.random.randint(1,100,10)
a

array([74, 64, 19, 41, 57, 16, 29, 40, 41,  3], dtype=int32)

In [90]:
a.sum()

np.int64(384)

In [91]:
a.max()

np.int32(74)

In [92]:
a.min()

np.int32(3)

In [93]:
a.argmax() #index of max element

np.int64(0)

In [94]:
a.argmin() #index of min element

np.int64(9)

In [95]:
a.mean()

np.float64(38.4)

In [96]:
b = np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [97]:
b.sum() 
#by default these operations are applied to the array as though it was a list of numbers, regardless of the shape

np.int64(36)

In [98]:
b.max()

np.int64(8)

In [99]:
b.min()

np.int64(0)

In [100]:
b.max(axis=1) #max of each row

array([2, 5, 8])

In [101]:
b.max(axis=0) #max of each col

array([6, 7, 8])

In [102]:
b.min(axis=1) #min of each row

array([0, 3, 6])

In [103]:
b.min(axis=0) #min of each col

array([0, 1, 2])

In [104]:
b.sum(axis=1) #sum of each row

array([ 3, 12, 21])

In [105]:
b.sum(axis=0) #sum of each col

array([ 9, 12, 15])

In [106]:
b.mean(axis=1) #mean of each row

array([1., 4., 7.])

In [107]:
b.mean(axis=0) #mean of each col

array([3., 4., 5.])

In [109]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
a[0]

np.int64(0)

In [111]:
for i in range(len(a)):
    print(a[i])

0
1
2
3
4
5
6
7
8
9


In [ ]:
a[1:5]
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
a[1:5:2]

array([1, 3])

In [116]:
a[1:5:2] = 100
a

array([  0, 100,   2, 100,   4,   5,   6,   7,   8,   9])

In [117]:
a[::-1]

array([  9,   8,   7,   6,   5,   4, 100,   2, 100,   0])

In [118]:
b = np.random.randint(10,50,(4,4))
b

array([[37, 22, 13, 44],
       [35, 35, 36, 16],
       [15, 44, 29, 42],
       [22, 10, 43, 47]], dtype=int32)

In [119]:
b[0]

array([37, 22, 13, 44], dtype=int32)

In [120]:
b[0,1]

np.int32(22)

In [122]:
b[:,:]

array([[37, 22, 13, 44],
       [35, 35, 36, 16],
       [15, 44, 29, 42],
       [22, 10, 43, 47]], dtype=int32)

In [123]:
b[:,0]

array([37, 35, 15, 22], dtype=int32)

In [124]:
b[:,1:3]

array([[22, 13],
       [35, 36],
       [44, 29],
       [10, 43]], dtype=int32)

In [125]:
b[:,[0,3]]

array([[37, 44],
       [35, 16],
       [15, 42],
       [22, 47]], dtype=int32)

In [126]:
b[:,:]

array([[37, 22, 13, 44],
       [35, 35, 36, 16],
       [15, 44, 29, 42],
       [22, 10, 43, 47]], dtype=int32)

In [127]:
b[1,:]

array([35, 35, 36, 16], dtype=int32)

In [128]:
b[1:3,:]

array([[35, 35, 36, 16],
       [15, 44, 29, 42]], dtype=int32)

In [130]:
b[[0,2,3],:]
b

array([[37, 22, 13, 44],
       [35, 35, 36, 16],
       [15, 44, 29, 42],
       [22, 10, 43, 47]], dtype=int32)

In [131]:
b[:2,:2]

array([[37, 22],
       [35, 35]], dtype=int32)

In [132]:
b[:2,2:]

array([[13, 44],
       [36, 16]], dtype=int32)

In [133]:
b[[0,2,3],:][:,[0,3]]
b

array([[37, 22, 13, 44],
       [35, 35, 36, 16],
       [15, 44, 29, 42],
       [22, 10, 43, 47]], dtype=int32)

In [139]:
file = open("sales_data.csv","w")
lines = file.readlines()
file.close()

UnsupportedOperation: not readable

In [140]:
data = [line.replace("\n","").split(",") for line in lines]
data

NameError: name 'lines' is not defined

In [141]:
data = np.array(data)
data

NameError: name 'data' is not defined

In [142]:
data[data[:,0]=='Sunday']

NameError: name 'data' is not defined

In [143]:
data[data[:,0]=='Sunday'][:,1:]

NameError: name 'data' is not defined

In [144]:
data[data[:,0]=='Sunday'][:,1:].astype("int64")

NameError: name 'data' is not defined

In [145]:
data[data[:,0]=='Sunday'][:,1:].astype("int64").mean(axis=0)

NameError: name 'data' is not defined

In [146]:
data[data[:,0]=='Sunday'][:,1:].astype("int64").mean(axis=0).argmax()

NameError: name 'data' is not defined

In [147]:
data[data[:,0]=='Sunday'][:,1:].astype("int64").mean(axis=0).argmin()

NameError: name 'data' is not defined