In [ ]:
import numpy as np

[5 7 9]


##### 1. Element-wise addition of 2 numpy arrays

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum = a + b
print(sum)

[5 7 9]


##### 2. Multiply Matrix by a scalar.

In [4]:
c = np.array([[1, 2], [3, 4]])
scalar = 3
prod_matrix = c * scalar
print(prod_matrix)

[[ 3  6]
 [ 9 12]]


##### 3. Create an Identity matrix

In [5]:
identity_matrix = np.eye(3)
print("3. Identity Matrix:\n", identity_matrix)

3. Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 4. Convert 1D array to 3D array

In [13]:
one_d_array = np.arange(12)
three_d_array = one_d_array.reshape(2, 2, 3)
print(three_d_array)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


##### 5. Convert data type from float to integer

In [14]:
float_array = np.array([1.2, 2.5, 3.8, 4.9])
int_array = float_array.astype(int)
print(int_array)

[1 2 3 4]


##### 6. Getting positions (indexes) where elements of 2 numpy arrays match

In [8]:
arr3 = np.array([1, 2, 3, 4, 5])
arr4 = np.array([5, 2, 3, 8, 5])
matching_indexes = np.where(arr3 == arr4)[0]
print("6. Matching indexes:", matching_indexes)

6. Matching indexes: [1 2 4]


##### 7. Matrix Generation with one particular value

In [15]:
matrix = np.full((3, 3), 7)
print(matrix)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


##### 8. Replace all odd numbers in the given array with -1

In [ ]:
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1 % 2 != 0] = -1
print(exercise_1)

8. Replaced odd numbers: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


##### 9. Get positions where elements of a and b match

In [11]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
matching_positions = np.where(a == b)[0]
print("9. Matching positions:", matching_positions)

9. Matching positions: [1 3 5 7]
